// GENERATED by scripts/generate-photo-manifest.mjs — do not edit by hand.
// Re-run it whenever a photo in public/ is added, replaced or re-cropped.
// The helpers that read this live in src/lib/photos.ts.

export type PhotoSize = { width: number; height: number };

export const PHOTO_SIZES: Record<string, PhotoSize> = {
  "/adizero-dropset-caio.webp": { width: 784, height: 1090 },
  "/adizero-dropset-cover.webp": { width: 1920, height: 1080 },
  "/adizero-dropset-hero.jpg": { width: 1280, height: 720 },
  "/adizero-dropset-pro-caio.webp": { width: 1200, height: 1500 },
  "/cape-town-hero.jpg": { width: 1672, height: 941 },
  "/crew-run.jpg": { width: 1350, height: 1800 },
  "/crew-suor.webp": { width: 1200, height: 1600 },
  "/founder-rio.webp": { width: 738, height: 1600 },
  "/half-marathon-record-hero.jpg": { width: 1400, height: 787 },
  "/hero-poster.jpg": { width: 1080, height: 1920 },
  "/home-track-hero.webp": { width: 1600, height: 900 },
  "/hyrox-hero.jpg": { width: 1206, height: 1624 },
  "/ikea-marathon-hero.avif": { width: 1200, height: 797 },
  "/june-shoe-drops-hero.webp": { width: 1672, height: 941 },
  "/race-hero.jpg": { width: 1600, height: 900 },
  "/road-run.jpg": { width: 1146, height: 1800 },
  "/run-and-lift-hero.webp": { width: 1600, height: 900 },
  "/run-club-hero.jpg": { width: 954, height: 534 },
  "/running-boom-hero.webp": { width: 1366, height: 768 },
  "/sao-silvestre-hero.webp": { width: 950, height: 593 },
  "/thais-oney.jpg": { width: 1135, height: 1101 },
  "/trail-run.jpg": { width: 1030, height: 1800 },
};
